### PR TITLE
Fix sorting ember posts

### LINKED ISSUE #1881: Reverse sorting of blog posts on Ember page
The posts appear oldest first but should start with the latest of course.

### PR DESCRIPTION
**Pull request by marcoow**
This fixes sorting of the Ember posts by explicitly defining the respective collection. I couldn't reproduce where the previously used collection even comes from – might be some kind of automatic thing that 11ty does based on Tags. This gives us a bit more freedom anyway.

closes #1881

### CODE REVIEW

File: collections/ember-posts.js [hunk 1]
```diff
@@ -0,0 +1,10 @@
+const livePosts = require("./posts");
+
+module.exports = collection => {
+  const allPosts = livePosts(collection);
+  return [
+    ...allPosts.filter(
+      post => Array.isArray(post.data.tags) && post.data.tags.some(t => t.match(/^ember\.?(js)?/))
+    ),
+  ];
```
Comment (BobrImperator) [inline collections/ember-posts.js]:
```suggestion
  return allPosts.filter(
      post => Array.isArray(post.data.tags) && post.data.tags.some(t => t.match(/^ember\.?(js)?/i))
    );
```

as per https://github.com/simplabs/mainmatter.com/pull/1885#discussion_r975060137

**Review by BobrImperator — APPROVED** [review]
